# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gRPC/grpc_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gRPC/grpc_config.proto',
  package='cb_grpc.msg.Main',
  syntax='proto3',
  serialized_options=_b('\n\032org.querc.cb_grpc.msg.grpcB\017ConfigCouchbaseP\001'),
  serialized_pb=_b('\n\x16gRPC/grpc_config.proto\x12\x10\x63\x62_grpc.msg.Main\"\x82\x02\n\x12InitiateConnection\x12\x13\n\x0b\x63lusterUser\x18\x01 \x01(\t\x12\x11\n\tclusterPW\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x16\n\x0e\x63lusterAddress\x18\x04 \x03(\t\x12\x11\n\tkvTimeout\x18\x05 \x01(\r\x12\x14\n\x0cqueryTimeout\x18\x06 \x01(\r\x12\x16\n\x0e\x44\x42MainPassword\x18\x07 \x01(\t\x12\x15\n\rDBTxnPassword\x18\x08 \x01(\t\x12\x15\n\rDBHxnPassword\x18\t \x01(\t\x12\x0e\n\x06\x44\x42Main\x18\n \x01(\t\x12\r\n\x05\x44\x42Txn\x18\x0b \x01(\t\x12\r\n\x05\x44\x42Hxn\x18\x0c \x01(\t\"$\n\x12\x43onnectionResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2j\n\x0f\x44\x61tabaseService\x12W\n\x07\x43onnect\x12$.cb_grpc.msg.Main.InitiateConnection\x1a$.cb_grpc.msg.Main.ConnectionResponse\"\x00\x42/\n\x1aorg.querc.cb_grpc.msg.grpcB\x0f\x43onfigCouchbaseP\x01\x62\x06proto3')
)




_INITIATECONNECTION = _descriptor.Descriptor(
  name='InitiateConnection',
  full_name='cb_grpc.msg.Main.InitiateConnection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clusterUser', full_name='cb_grpc.msg.Main.InitiateConnection.clusterUser', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clusterPW', full_name='cb_grpc.msg.Main.InitiateConnection.clusterPW', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='cb_grpc.msg.Main.InitiateConnection.version', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clusterAddress', full_name='cb_grpc.msg.Main.InitiateConnection.clusterAddress', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kvTimeout', full_name='cb_grpc.msg.Main.InitiateConnection.kvTimeout', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='queryTimeout', full_name='cb_grpc.msg.Main.InitiateConnection.queryTimeout', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='DBMainPassword', full_name='cb_grpc.msg.Main.InitiateConnection.DBMainPassword', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='DBTxnPassword', full_name='cb_grpc.msg.Main.InitiateConnection.DBTxnPassword', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='DBHxnPassword', full_name='cb_grpc.msg.Main.InitiateConnection.DBHxnPassword', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='DBMain', full_name='cb_grpc.msg.Main.InitiateConnection.DBMain', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='DBTxn', full_name='cb_grpc.msg.Main.InitiateConnection.DBTxn', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='DBHxn', full_name='cb_grpc.msg.Main.InitiateConnection.DBHxn', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=303,
)


_CONNECTIONRESPONSE = _descriptor.Descriptor(
  name='ConnectionResponse',
  full_name='cb_grpc.msg.Main.ConnectionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='cb_grpc.msg.Main.ConnectionResponse.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=305,
  serialized_end=341,
)

DESCRIPTOR.message_types_by_name['InitiateConnection'] = _INITIATECONNECTION
DESCRIPTOR.message_types_by_name['ConnectionResponse'] = _CONNECTIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InitiateConnection = _reflection.GeneratedProtocolMessageType('InitiateConnection', (_message.Message,), dict(
  DESCRIPTOR = _INITIATECONNECTION,
  __module__ = 'gRPC.grpc_config_pb2'
  # @@protoc_insertion_point(class_scope:cb_grpc.msg.Main.InitiateConnection)
  ))
_sym_db.RegisterMessage(InitiateConnection)

ConnectionResponse = _reflection.GeneratedProtocolMessageType('ConnectionResponse', (_message.Message,), dict(
  DESCRIPTOR = _CONNECTIONRESPONSE,
  __module__ = 'gRPC.grpc_config_pb2'
  # @@protoc_insertion_point(class_scope:cb_grpc.msg.Main.ConnectionResponse)
  ))
_sym_db.RegisterMessage(ConnectionResponse)


DESCRIPTOR._options = None

_DATABASESERVICE = _descriptor.ServiceDescriptor(
  name='DatabaseService',
  full_name='cb_grpc.msg.Main.DatabaseService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=343,
  serialized_end=449,
  methods=[
  _descriptor.MethodDescriptor(
    name='Connect',
    full_name='cb_grpc.msg.Main.DatabaseService.Connect',
    index=0,
    containing_service=None,
    input_type=_INITIATECONNECTION,
    output_type=_CONNECTIONRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATABASESERVICE)

DESCRIPTOR.services_by_name['DatabaseService'] = _DATABASESERVICE

# @@protoc_insertion_point(module_scope)
