# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import grpc_query_pb2 as grpc__query__pb2


class QueryServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.n1qlQuery = channel.unary_unary(
        '/cb_grpc.msg.Main.QueryService/n1qlQuery',
        request_serializer=grpc__query__pb2.Query.SerializeToString,
        response_deserializer=grpc__query__pb2.QueryResponse.FromString,
        )
    self.kvGet = channel.unary_unary(
        '/cb_grpc.msg.Main.QueryService/kvGet',
        request_serializer=grpc__query__pb2.DocID.SerializeToString,
        response_deserializer=grpc__query__pb2.QueryResponse.FromString,
        )
    self.kvDelete = channel.unary_unary(
        '/cb_grpc.msg.Main.QueryService/kvDelete',
        request_serializer=grpc__query__pb2.DocID.SerializeToString,
        response_deserializer=grpc__query__pb2.QueryResponse.FromString,
        )
    self.kvPut = channel.unary_unary(
        '/cb_grpc.msg.Main.QueryService/kvPut',
        request_serializer=grpc__query__pb2.JsonID.SerializeToString,
        response_deserializer=grpc__query__pb2.QueryResponse.FromString,
        )
    self.kvUpsert = channel.unary_unary(
        '/cb_grpc.msg.Main.QueryService/kvUpsert',
        request_serializer=grpc__query__pb2.JsonID.SerializeToString,
        response_deserializer=grpc__query__pb2.QueryResponse.FromString,
        )


class QueryServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def n1qlQuery(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def kvGet(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def kvDelete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def kvPut(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def kvUpsert(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_QueryServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'n1qlQuery': grpc.unary_unary_rpc_method_handler(
          servicer.n1qlQuery,
          request_deserializer=grpc__query__pb2.Query.FromString,
          response_serializer=grpc__query__pb2.QueryResponse.SerializeToString,
      ),
      'kvGet': grpc.unary_unary_rpc_method_handler(
          servicer.kvGet,
          request_deserializer=grpc__query__pb2.DocID.FromString,
          response_serializer=grpc__query__pb2.QueryResponse.SerializeToString,
      ),
      'kvDelete': grpc.unary_unary_rpc_method_handler(
          servicer.kvDelete,
          request_deserializer=grpc__query__pb2.DocID.FromString,
          response_serializer=grpc__query__pb2.QueryResponse.SerializeToString,
      ),
      'kvPut': grpc.unary_unary_rpc_method_handler(
          servicer.kvPut,
          request_deserializer=grpc__query__pb2.JsonID.FromString,
          response_serializer=grpc__query__pb2.QueryResponse.SerializeToString,
      ),
      'kvUpsert': grpc.unary_unary_rpc_method_handler(
          servicer.kvUpsert,
          request_deserializer=grpc__query__pb2.JsonID.FromString,
          response_serializer=grpc__query__pb2.QueryResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'cb_grpc.msg.Main.QueryService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
