# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: database/bom.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='database/bom.proto',
  package='org.querc.cb_grpc.msg.bom',
  syntax='proto3',
  serialized_options=_b('\n\025org.querc.cb_grpc.msgB\003Bom'),
  serialized_pb=_b('\n\x12\x64\x61tabase/bom.proto\x12\x19org.querc.cb_grpc.msg.bom\"\x08\n\x06NewBomB\x1c\n\x15org.querc.cb_grpc.msgB\x03\x42omb\x06proto3')
)




_NEWBOM = _descriptor.Descriptor(
  name='NewBom',
  full_name='org.querc.cb_grpc.msg.bom.NewBom',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=57,
)

DESCRIPTOR.message_types_by_name['NewBom'] = _NEWBOM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NewBom = _reflection.GeneratedProtocolMessageType('NewBom', (_message.Message,), dict(
  DESCRIPTOR = _NEWBOM,
  __module__ = 'database.bom_pb2'
  # @@protoc_insertion_point(class_scope:org.querc.cb_grpc.msg.bom.NewBom)
  ))
_sym_db.RegisterMessage(NewBom)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
